import tseslint from "typescript-eslint";

export default tseslint.config(
  // dist is generated by ncc and committed on purpose; it is not linted.
  { ignores: ["dist", "coverage"] },
  { files: ["*.config.js"], ...tseslint.configs.disableTypeChecked },
  {
    files: ["src/**/*.ts", "test/**/*.ts"],
    extends: [
      ...tseslint.configs.strictTypeChecked,
      ...tseslint.configs.stylisticTypeChecked,
    ],
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
  },
);
